#:import MDTextField kivymd.textfields.MDTextField
#:import TwoLineListItem kivymd.list.TwoLineListItem
#:import ChannelChatTab app.component.channel_chat_tab

<Row@BoxLayout>:
    username: ''
    message: ''
    TwoLineListItem:
        text: "@"+root.username
        secondary_text: root.message


<ChatScreen>:
    tab_panel: tab_panel

    MDTabbedPanel:
        id: tab_panel
        tab_display_mode:'text'
